# Generated by Django 3.2.7 on 2021-10-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100)),
                ('device_manufacturer', models.CharField(max_length=100)),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NM.devicecategories')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('client_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('banner_motd', models.TextField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NM.devices')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NM.projects')),
            ],
        ),
    ]
