# Generated by Django 3.2.7 on 2021-11-18 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isr4321',
            old_name='g00_ip',
            new_name='g00_ipv4',
        ),
    ]
