# Generated by Django 3.2.7 on 2021-11-10 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NM', '0002_auto_20211109_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isr4321',
            name='algo',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='bgp_ipv6_neighbor_wan_ip_out',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='bgp_ipv6_neighbor_wan_route_map_out',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='key_string',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='keychain_name',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='match_https',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='match_icmp',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='match_ssh',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='match_tcp',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='match_udp',
        ),
        migrations.RemoveField(
            model_name='isr4321',
            name='nat_inside_list',
        ),
        migrations.AddField(
            model_name='isr4321',
            name='bgp_ipv4_community',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isr4321',
            name='bgp_ipv6_community',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isr4321',
            name='next_hop_router',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isr4321',
            name='next_hop_wan',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='isr4321',
            name='bgp_ipv6_network',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='isr4321',
            name='bgp_ipv6_subnet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='banner_motd',
            field=models.CharField(max_length=100),
        ),
    ]
