# Generated by Django 3.2.7 on 2021-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0002_auto_20211021_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='date_modified',
            field=models.DateField(auto_now_add=True),
        ),
    ]
