# Generated by Django 3.2.7 on 2021-11-10 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NM', '0003_auto_20211110_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
        migrations.AddField(
            model_name='scripts',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scripts',
            name='date_modified',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
