# Generated by Django 3.2.7 on 2021-11-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0003_rename_g01_ip_isr4321_g01_ipv4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isr4321',
            old_name='g02_ip',
            new_name='g02_ipv4',
        ),
    ]
