# Generated by Django 3.2.7 on 2021-11-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0004_rename_g02_ip_isr4321_g02_ipv4'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='nm_model',
            field=models.CharField(default='asdas', max_length=100),
            preserve_default=False,
        ),
    ]
