# Generated by Django 3.2.7 on 2021-10-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0004_auto_20211022_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=100)),
                ('organisation_usergroup', models.CharField(max_length=100)),
            ],
        ),
    ]
