# Generated by Django 3.2.7 on 2021-11-10 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NM', '0004_auto_20211110_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripts',
            name='banner_motd',
        ),
        migrations.RemoveField(
            model_name='scripts',
            name='host_name',
        ),
        migrations.AddField(
            model_name='isr4321',
            name='banner_motd',
            field=models.CharField(default='This is C1-R1. Unauthorised Access strictly prohibited.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isr4321',
            name='host_name',
            field=models.CharField(default='C1-R1', max_length=100),
            preserve_default=False,
        ),
    ]
