# Generated by Django 3.2.7 on 2021-11-23 03:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0005_devices_nm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='C1000',
            fields=[
                ('scripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NM.scripts')),
                ('host_name', models.CharField(max_length=100)),
                ('vlans', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=models.CharField(max_length=100)), size=None)),
            ],
            bases=('NM.scripts',),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
