# Generated by Django 3.2.7 on 2021-10-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0005_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='NM.organisation'),
        ),
    ]
