# Generated by Django 3.2.7 on 2021-11-10 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NM', '0005_auto_20211110_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isr4321',
            old_name='g01_ospfv3_ipv6_area',
            new_name='g01_ospfv3_v6_area',
        ),
        migrations.RenameField(
            model_name='isr4321',
            old_name='g02_ospfv3_ipv6_area',
            new_name='g02_ospfv3_v6_area',
        ),
        migrations.RenameField(
            model_name='isr4321',
            old_name='isakmp_ipv6_remote_peer',
            new_name='isakmp_ipv6_remote_peer_ip',
        ),
        migrations.RenameField(
            model_name='isr4321',
            old_name='isakmp_match_ipv6',
            new_name='isakmp_match_ipv6_add',
        ),
        migrations.RenameField(
            model_name='isr4321',
            old_name='nat_acl_permit',
            new_name='nat_acl_permit_ip',
        ),
        migrations.RenameField(
            model_name='isr4321',
            old_name='login_tries_time',
            new_name='tries_time',
        ),
        
    ]
