# Generated by Django 3.2.7 on 2021-11-23 18:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0005_devices_nm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSC3650',
            fields=[
                ('scripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NM.scripts')),
                ('host_name', models.CharField(max_length=100)),
                ('banner_motd', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('login_block_time', models.IntegerField()),
                ('login_tries', models.IntegerField()),
                ('tries_time', models.IntegerField()),
                ('login_delay', models.IntegerField()),
                ('login_access', models.GenericIPAddressField()),
                ('default_gateway', models.GenericIPAddressField()),
                ('dhcp_excluded', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), size=None)),
                ('radius_server', models.CharField(max_length=100)),
                ('radius_ip', models.GenericIPAddressField()),
                ('radius_key', models.CharField(max_length=100)),
                ('radius_group', models.CharField(max_length=100)),
                ('ntp_server', models.GenericIPAddressField()),
                ('ntp_auth_key', models.IntegerField()),
                ('ntp_pass', models.CharField(max_length=100)),
                ('ntp_trust_key', models.IntegerField()),
            ],
            bases=('NM.scripts',),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VLAN_C3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('ipv4_address', models.GenericIPAddressField()),
                ('ipv4_subnet', models.GenericIPAddressField()),
                ('ipv6_address', models.GenericIPAddressField()),
                ('ipv6_prefix', models.IntegerField()),
                ('ipv6_link', models.GenericIPAddressField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='STP_VLAN_3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan', models.IntegerField()),
                ('root', models.CharField(max_length=9)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='OSPFv3_3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=10)),
                ('router_id', models.GenericIPAddressField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='Interface_C3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('switchport', models.CharField(max_length=2)),
                ('ipv4_address', models.GenericIPAddressField()),
                ('ipv4_subnet', models.GenericIPAddressField()),
                ('ipv6_address', models.GenericIPAddressField()),
                ('ipv6_prefix', models.IntegerField()),
                ('ipv6_link', models.GenericIPAddressField()),
                ('sw_mode', models.CharField(max_length=10)),
                ('sw_access', models.IntegerField()),
                ('allowed_vlan', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('native_vlan', models.IntegerField()),
                ('encapsulation', models.CharField(max_length=5)),
                ('nonegotiate', models.CharField(max_length=2)),
                ('channel_group', models.IntegerField()),
                ('channel_mode', models.CharField(max_length=10)),
                ('stp_cost', models.IntegerField(verbose_name=1)),
                ('ipv4_ospfv3', models.CharField(max_length=10)),
                ('ipv4_area', models.IntegerField()),
                ('ipv6_ospfv3', models.CharField(max_length=10)),
                ('ipv6_area', models.IntegerField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='DHCP_3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network_ip', models.GenericIPAddressField()),
                ('network_subnet', models.GenericIPAddressField()),
                ('default_router', models.GenericIPAddressField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='CiscoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='ACL_3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permit', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), size=None)),
                ('deny', django.contrib.postgres.fields.ArrayField(base_field=models.GenericIPAddressField(), size=None)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
    ]
