# Generated by Django 3.2.7 on 2021-11-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0006_auto_20211124_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_c3650',
            name='allowed_vlan',
            field=models.CharField(max_length=100),
        ),
    ]
