# Generated by Django 3.2.7 on 2021-10-28 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('NM', '0006_projects_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
