# Generated by Django 3.2.7 on 2021-11-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0004_auto_20211110_1949'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='isr4321',
            name='g00_ipv6_vrrp_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='isr4321',
            name='g00_vrrp_address',
            field=models.CharField(max_length=100),
        ),
    ]
