# Generated by Django 3.2.7 on 2021-11-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0007_alter_interface_c3650_allowed_vlan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acl_3650',
            name='deny',
        ),
        migrations.RemoveField(
            model_name='acl_3650',
            name='permit',
        ),
        migrations.CreateModel(
            name='DHCP_EX_C3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='ACL_EL_3650',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('address', models.GenericIPAddressField()),
                ('acl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.acl_3650')),
            ],
        ),
    ]
