# Generated by Django 3.2.7 on 2021-11-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0008_auto_20211124_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsc3650',
            name='dhcp_excluded',
        ),
    ]
