# Generated by Django 3.2.7 on 2021-11-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0004_auto_20211022_0758'),
        ('NM', '0008_auto_20211118_1340'),
    ]

    operations = [
    ]
