# Generated by Django 3.2.7 on 2021-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0009_merge_0004_auto_20211022_0758_0008_auto_20211118_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='isr4321',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
    
