# Generated by Django 3.2.7 on 2021-11-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0009_remove_wsc3650_dhcp_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsc3650',
            name='max_fail',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
