# Generated by Django 3.2.7 on 2021-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isr4321',
            name='current_time',
        ),
    ]
    
