# Generated by Django 3.2.7 on 2021-11-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0012_wsc3650_min_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wsc3650',
            name='radius_group',
        ),
    ]
