# Generated by Django 3.2.7 on 2021-11-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0013_remove_wsc3650_radius_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsc3650',
            name='radius_group',
            field=models.CharField(default='radius_group', max_length=100),
            preserve_default=False,
        ),
    ]
