# Generated by Django 3.2.7 on 2021-11-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0014_wsc3650_radius_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wsc3650',
            name='login_access',
            field=models.CharField(max_length=100),
        ),
    ]
