# Generated by Django 3.2.7 on 2021-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0015_alter_wsc3650_login_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_c3650',
            name='allowed_vlan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='channel_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='channel_mode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='encapsulation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv4_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv4_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv4_ospfv3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv4_subnet',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_link',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_ospfv3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_prefix',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='native_vlan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='nonegotiate',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='status',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='stp_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='sw_access',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='sw_mode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='switchport',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vlan_c3650',
            name='ipv4_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='vlan_c3650',
            name='ipv4_subnet',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='vlan_c3650',
            name='ipv6_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='vlan_c3650',
            name='ipv6_link',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='vlan_c3650',
            name='ipv6_prefix',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vlan_c3650',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
