# Generated by Django 3.2.7 on 2021-11-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0016_auto_20211125_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_c3650',
            name='channel_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv4_area',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_area',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='native_vlan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='stp_cost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interface_c3650',
            name='sw_access',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
