# Generated by Django 3.2.7 on 2021-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0017_auto_20211125_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_prefix',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
