# Generated by Django 3.2.7 on 2021-11-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0018_alter_interface_c3650_ipv6_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_c3650',
            name='ipv6_prefix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
