# Generated by Django 3.2.7 on 2021-11-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0024_auto_20211125_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
