# Generated by Django 3.2.7 on 2021-11-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0026_alter_scripts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
