# Generated by Django 3.2.7 on 2021-11-25 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0027_alter_scripts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
