# Generated by Django 3.2.7 on 2021-11-25 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0030_auto_20211126_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
