# Generated by Django 3.2.7 on 2021-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0031_alter_scripts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
