# Generated by Django 3.2.7 on 2021-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0032_alter_scripts_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
