# Generated by Django 3.2.7 on 2021-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0033_alter_scripts_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
