# Generated by Django 3.2.7 on 2021-11-26 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0034_alter_scripts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 16, 9, 9, 72727, tzinfo=utc)),
        ),
    ]
