# Generated by Django 3.2.7 on 2021-11-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0037_alter_scripts_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='C1000',
            fields=[
                ('scripts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NM.scripts')),
                ('host_name', models.CharField(max_length=100)),
                ('banner_motd', models.CharField(max_length=100)),
                ('min_length', models.IntegerField()),
                ('secret', models.CharField(max_length=100)),
                ('login_block_time', models.IntegerField()),
                ('login_tries', models.IntegerField()),
                ('tries_time', models.IntegerField()),
                ('login_delay', models.IntegerField()),
                ('login_access', models.CharField(max_length=100)),
                ('stp_mode', models.CharField(max_length=100)),
                ('radius_server', models.CharField(max_length=100)),
                ('radius_group', models.CharField(max_length=100)),
                ('radius_ip', models.GenericIPAddressField()),
                ('radius_key', models.CharField(max_length=100)),
                ('max_fail', models.IntegerField()),
                ('ntp_server', models.GenericIPAddressField()),
                ('ntp_auth_key', models.IntegerField()),
                ('ntp_pass', models.CharField(max_length=100)),
                ('ntp_trust_key', models.IntegerField()),
            ],
            bases=('NM.scripts',),
        ),
        migrations.CreateModel(
            name='VLAN_C1000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
        migrations.CreateModel(
            name='Interface_C1000',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sw_mode', models.CharField(max_length=10, null=True)),
                ('sw_access', models.CharField(max_length=100, null=True)),
                ('allowed_vlan', models.CharField(max_length=100, null=True)),
                ('native_vlan', models.CharField(max_length=100, null=True)),
                ('channel_group', models.CharField(max_length=100, null=True)),
                ('channel_mode', models.CharField(max_length=10, null=True)),
                ('bdpu_filter', models.CharField(max_length=10, null=True)),
                ('bdpu_guard', models.CharField(max_length=10, null=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NM.wsc3650')),
            ],
        ),
    ]
