# Generated by Django 3.2.7 on 2021-11-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NM', '0039_auto_20211128_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isr4321',
            name='g01_ospfv3_encryption_sha',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='isr4321',
            name='g02_ospfv3_encryption_sha',
            field=models.CharField(max_length=40),
        ),
    ]
